name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/image_1.png
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/iconbattery_full_4_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/live_connection_x2.svg
  - assets/vectors/icon_39_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/iconbattery_full_19_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/images/rectangle_11.jpeg
  - assets/images/rectangle_14.jpeg
  - assets/images/rectangle_12.jpeg
  - assets/images/rectangle_10.jpeg
  - assets/images/ellipse_12.jpeg
  - assets/images/rectangle_13.jpeg
  - assets/images/rectangle_9.jpeg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/icon_18_x2.svg
  - assets/vectors/icon_19_x2.svg
  - assets/vectors/iconbattery_full_12_x2.svg
  - assets/vectors/icon_43_x2.svg
  - assets/vectors/ellipse_11_x2.svg
  - assets/vectors/iconbattery_full_13_x2.svg
  - assets/vectors/icon_25_x2.svg
  - assets/vectors/icon_29_x2.svg
  - assets/images/airdrop.png
  - assets/vectors/icon_33_x2.svg
  - assets/vectors/icon_x2.svg
  - assets/vectors/icon_27_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/iconbattery_full_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/vectors/icon_35_x2.svg
  - assets/vectors/check_circle_3_x2.svg
  - assets/vectors/email_1_x2.svg
  - assets/images/whats_app_image_20240827_at_000415_e_194_f_680.jpeg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/iconbattery_full_16_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/check_circle_6_x2.svg
  - assets/vectors/check_circle_2_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/iconbattery_full_5_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/iconbattery_full_6_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/images/rectangle_7.jpeg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/iconbattery_full_20_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/images/ellipse_12.jpeg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/icon_2_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/iconbattery_full_1_x2.svg
  - assets/vectors/person_1_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/iconbattery_full_22_x2.svg
  - assets/vectors/icon_31_x2.svg
  - assets/vectors/icon_11_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/icon_9_x2.svg
  - assets/vectors/icon_14_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/images/whats_app_image_20240827_at_00041650210_cb_5.jpeg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/iconbattery_full_15_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/rectangle_15_stroke_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/icon_24_x2.svg
  - assets/vectors/iconbattery_full_8_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/rectangle_15_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/iconbattery_full_2_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/icon_26_x2.svg
  - assets/vectors/icon_32_x2.svg
  - assets/vectors/icon_48_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/icon_3_x2.svg
  - assets/vectors/icon_7_x2.svg
  - assets/vectors/icon_13_x2.svg
  - assets/vectors/icon_30_x2.svg
  - assets/vectors/icon_49_x2.svg
  - assets/vectors/icon_8_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/iconbattery_full_17_x2.svg
  - assets/images/whats_app_image_20240827_at_000416829336_a_0.jpeg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/iconbattery_full_7_x2.svg
  - assets/images/rectangle_10.jpeg
  - assets/images/rectangle_14.jpeg
  - assets/images/rectangle_9.jpeg
  - assets/images/rectangle_12.jpeg
  - assets/images/rectangle_13.jpeg
  - assets/images/rectangle_11.jpeg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/icon_16_x2.svg
  - assets/vectors/icon_17_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/iconbattery_full_18_x2.svg
  - assets/vectors/check_circle_1_x2.svg
  - assets/images/rectangle_7.jpeg
  - assets/vectors/check_circle_x2.svg
  - assets/vectors/check_circle_4_x2.svg
  - assets/vectors/iconbattery_full_21_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/password_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/iconbattery_full_3_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/email_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/person_x2.svg
  - assets/images/check_mate_logo.png
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/icon_50_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/icon_5_x2.svg
  - assets/vectors/icon_44_x2.svg
  - assets/vectors/icon_28_x2.svg
  - assets/vectors/password_1_x2.svg
  - assets/vectors/icon_6_x2.svg
  - assets/vectors/icon_46_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/iconbattery_full_14_x2.svg
  - assets/vectors/icon_41_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/icon_45_x2.svg
  - assets/vectors/person_2_x2.svg
  - assets/vectors/check_circle_5_x2.svg
  - assets/images/whats_app_image_20240827_at_000417_dd_9460_c_0.jpeg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/iconbattery_full_9_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/images/rectangle_70.jpeg
  - assets/images/rectangle_71.jpeg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/iconbattery_full_11_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/icon_36_x2.svg

